{% set name = "pytorch-tabnet" %}
{% set version = "4.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dreamquark-ai/tabnet/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0703d0298bf605dae289515023859428017fe86e4663de9068a99f06b9802c94

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python
    - poetry >=0.12
  run:
    - python
    - numpy >=1.17,<2.0
    - scikit-learn >0.21
    - scipy >1.4
    - pytorch >=1.2,<2.0
    - tqdm >=4.36,<5.0

test:
  imports:
    - pytorch_tabnet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dreamquark-ai/tabnet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyTorch implementation of TabNet
  description: |
    This is a pyTorch implementation of Tabnet (Arik, S. O., & Pfister, T. (2019). 
    TabNet: Attentive Interpretable Tabular Learning. arXiv preprint arXiv:1908.07442.) 
    https://arxiv.org/pdf/1908.07442.pdf.
  dev_url: https://github.com/dreamquark-ai/tabnet
  doc_url: https://dreamquark-ai.github.io/tabnet/

extra:
  recipe-maintainers:
    - sugatoray
    - Optimox
    - Hartorn
    - eduardocarvp
